spring.application.name=service-offering-service

server.port=5004

spring.datasource.url=jdbc:postgresql://localhost:5432/service-offering
spring.datasource.username=postgres
spring.datasource.password=Alinogy7
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
